#!/usr/bin/env python3
"""Deterministically generate the excluded V-2 calibration corpus.

Detector Reviewer finding 12: ``routing_corpus.json`` named a calibration
manifest at ``tests/fixtures/gold/calibration-manifest.json`` that did not
exist, so the gate's calibration obligation could be satisfied by a refusal.

``spec/verification.md`` V-2:

    Before V-10, run a separate excluded 60-message calibration corpus through
    the same five-run configuration.

This tool is run by the Tester and its output is committed. The suite never runs
it: it reads the frozen bytes and checks their digest, so a later edit to the
generator cannot silently move the corpus. Regenerating must reproduce the
committed bytes exactly.

    tests/tools/freeze-calibration.py --check     # verify committed bytes
    tests/tools/freeze-calibration.py --write     # regenerate
"""
from __future__ import annotations

import hashlib
import json
import random
import sys
from pathlib import Path

SEED = 20260907
COUNT = 60
HERE = Path(__file__).resolve().parent.parent
CORPUS = HERE / "fixtures" / "gold" / "calibration_corpus.json"
MANIFEST = HERE / "fixtures" / "gold" / "calibration-manifest.json"

#: Stratum draw order. Twenty codebase and twenty company messages give each
#: shared destination 100 pooled trials across the five preregistered runs, which
#: is what the ratified Wilson 0.95 lower bound needs to be reachable at all: a
#: 60-message single-run denominator caps the bound at 0.94 even for a perfect
#: classifier, so a thinner corpus would fail V-2 by construction.
STRATA = (
    ("codebase_fact", ("codebase",)),
    ("company_architecture", ("company",)),
    ("codebase_fact", ("codebase",)),
    ("company_architecture", ("company",)),
    ("ambiguous_non_fact", ("none",)),
    ("temporary_suggestion", ("none",)),
)

SUBJECTS = (
    "scheduler lookahead", "retry ceiling", "queue drain order", "cache warmup",
    "shard rebalance", "backpressure threshold", "replay window", "fanout budget",
    "index compaction", "leader lease",
)

CODEBASE = "in this repository {subject} is bounded by the checked-in default"
COMPANY = "the architecture board fixed {subject} for every service"
AMBIGUOUS = "someone mentioned {subject} in passing without deciding anything"
TEMPORARY = "for today only we are nudging {subject} while the incident runs"
PERSONAL = "my own note about {subject} that belongs in the personal store"

TEMPLATES = {
    "codebase_fact": CODEBASE,
    "company_architecture": COMPANY,
    "ambiguous_non_fact": AMBIGUOUS,
    "temporary_suggestion": TEMPORARY,
}


def build() -> dict:
    rng = random.Random(SEED)
    messages = []
    for index in range(COUNT):
        stratum, destinations = STRATA[index % len(STRATA)]
        subject = SUBJECTS[rng.randrange(len(SUBJECTS))]
        text = TEMPLATES[stratum].format(subject=subject)
        atoms = [["constraint", text, list(destinations)]]
        mixed = index % 5 == 0 and stratum in ("codebase_fact", "company_architecture")
        if mixed:
            personal = PERSONAL.format(subject=subject)
            text = text + ". " + personal
            atoms.append(["preference", personal, ["personal"]])
        messages.append({
            "message_id": f"cal{index:03d}",
            "stratum": stratum,
            "subject": subject,
            "mixed": mixed,
            "template": text + ".",
            "gold_atoms": atoms,
            "canary_slots": [],
        })
    payload = {
        "schema": "guildhall-v2-calibration-corpus/1",
        "shared_destination_messages_per_label": 20,
        "pooled_trials_per_shared_label_across_five_runs": 100,
        "generator": "tests/tools/freeze-calibration.py",
        "seed": SEED,
        "message_count": COUNT,
        "strata": sorted({s for s, _ in STRATA}),
        "provenance": (
            "Deterministically generated by the Tester from the named seed above. "
            "Excluded from the held-out routing corpus by construction: its "
            "identifiers are the cal* namespace and share no id with the m* "
            "held-out namespace. Contains no real private conversation."
        ),
        "messages": messages,
    }
    return payload


def canonical(payload: dict) -> bytes:
    return (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode("utf-8")


def manifest_for(raw: bytes, payload: dict) -> bytes:
    document = {
        "schema": "guildhall-v2-calibration-manifest/1",
        "corpus_path": "tests/fixtures/gold/calibration_corpus.json",
        "corpus_sha256": hashlib.sha256(raw).hexdigest(),
        "message_count": payload["message_count"],
        "seed": payload["seed"],
        "generator": payload["generator"],
        "frozen_before": (
            "any classifier run; spec/verification.md V-2 requires the "
            "calibration corpus to gate expensive measurement"
        ),
        "held_out_namespace": "m*",
        "calibration_namespace": "cal*",
        "thresholds": {
            "macro_f1_lower_bound": 0.90,
            "shared_precision_lower_bound": 0.95,
            "macro_f1_interval_method": "message_stratified_bootstrap",
            "shared_precision_interval_method": "wilson",
        },
    }
    return (json.dumps(document, indent=2, sort_keys=True) + "\n").encode("utf-8")


def main() -> int:
    payload = build()
    raw = canonical(payload)
    manifest = manifest_for(raw, payload)
    if "--write" in sys.argv:
        CORPUS.write_bytes(raw)
        MANIFEST.write_bytes(manifest)
        print(f"wrote {CORPUS} ({hashlib.sha256(raw).hexdigest()[:16]})")
        print(f"wrote {MANIFEST}")
        return 0
    ok = CORPUS.is_file() and CORPUS.read_bytes() == raw
    ok = ok and MANIFEST.is_file() and MANIFEST.read_bytes() == manifest
    print("reproduces committed bytes" if ok else "DIVERGED from committed bytes")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
