"""The excluded 60-message calibration corpus and its frozen manifest.

Detector Reviewer finding 12. ``routing_corpus.json`` named a calibration
manifest that did not exist on disk, so ``spec/verification.md`` V-2's

    Before V-10, run a separate excluded 60-message calibration corpus through
    the same five-run configuration.

was satisfied by a refusal: the gate observed "no calibration input" and passed.

The corpus is now committed, deterministically generated by
``tests/tools/freeze-calibration.py`` from a named seed, and bound to a manifest
that pins its digest and both thresholds. This module loads it, proves the
committed bytes match the manifest digest, proves zero overlap with the held-out
corpus, and binds it for the product through the same gold-stripping path the
held-out corpus uses.

Absence of any of those is :class:`~acceptance._harness.prereq.PrerequisiteMissing`
--- an instrument condition. A calibration corpus the instrument cannot produce
is not a product failure and is certainly not a pass.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping

from . import prereq
from .corpora import BoundCorpus, _emit, load_gold
from . import synth
from .worldbuilder import OpaqueIds

CORPUS_NAME = "calibration_corpus.json"
MANIFEST_NAME = "calibration-manifest.json"
REQUIRED_MESSAGES = 60


def _gold_dir() -> Path:
    return Path(__file__).resolve().parents[2] / "fixtures" / "gold"


@dataclass(frozen=True)
class CalibrationManifest:
    """The frozen manifest binding the corpus bytes and both thresholds."""

    path: Path
    document: Mapping[str, Any]

    @property
    def corpus_sha256(self) -> str:
        return str(self.document["corpus_sha256"])

    @property
    def macro_f1_floor(self) -> float:
        return float(self.document["thresholds"]["macro_f1_lower_bound"])

    @property
    def shared_precision_floor(self) -> float:
        return float(self.document["thresholds"]["shared_precision_lower_bound"])

    def as_json(self) -> dict:
        return dict(self.document)


def load_manifest() -> CalibrationManifest:
    path = _gold_dir() / MANIFEST_NAME
    raw = prereq.fixture_file(
        path, why="spec/verification.md V-2 requires a separate excluded "
                  "calibration corpus, frozen before any classifier run",
        minimum_bytes=64,
    )
    document = json.loads(raw.decode("utf-8"))
    for key in ("corpus_sha256", "message_count", "thresholds", "corpus_path"):
        if key not in document:
            raise prereq.missing(
                "fixture", str(path), f"manifest is missing {key!r}"
            )
    return CalibrationManifest(path=path, document=document)


def load_corpus() -> dict:
    manifest = load_manifest()
    path = _gold_dir() / CORPUS_NAME
    raw = prereq.fixture_file(
        path, why="the calibration corpus named by the frozen manifest",
        minimum_bytes=1024,
    )
    observed = hashlib.sha256(raw).hexdigest()
    if observed != manifest.corpus_sha256:
        raise prereq.missing(
            "fixture", str(path),
            f"corpus digest {observed} does not match the manifest digest "
            f"{manifest.corpus_sha256}; the frozen calibration set moved",
        )
    payload = json.loads(raw.decode("utf-8"))
    messages = payload.get("messages")
    if not isinstance(messages, list) or len(messages) != REQUIRED_MESSAGES:
        raise prereq.missing(
            "fixture", str(path),
            f"{len(messages) if isinstance(messages, list) else 0} message(s); "
            f"V-2 requires exactly {REQUIRED_MESSAGES}",
        )
    return payload


def overlap_with_held_out() -> tuple[str, ...]:
    """Identifiers shared with the held-out corpus. Must be empty."""
    calibration = {m["message_id"] for m in load_corpus()["messages"]}
    held_out = {m["message_id"] for m in load_gold("routing_corpus.json")["messages"]}
    return tuple(sorted(calibration & held_out))


def bind(destination: Path, *, seed: bytes | None = None) -> BoundCorpus:
    """Instantiate the calibration corpus for the product, gold stripped.

    The product receives ``{id, role, text, observed_at, source_kind}`` under an
    opaque per-run identifier and nothing else, exactly as the held-out corpus
    does, so the same classifier configuration can run over both.
    """
    payload = load_corpus()
    ids = OpaqueIds(seed)
    records: list[dict] = []
    gold: dict[str, dict] = {}
    for message in payload["messages"]:
        token = ids.token(message["message_id"])
        records.append({
            "id": token,
            "role": "user",
            "text": message["template"],
            "observed_at": synth.receipt_stamp(),
            "source_kind": "codex_jsonl",
        })
        gold[token] = {
            "atoms": message["gold_atoms"],
            "mixed": bool(message["mixed"]),
            "stratum": message["stratum"],
            "canary_slots": [],
            "destinations": sorted(
                {d for _, _, ds in message["gold_atoms"] for d in ds}
            ),
        }
    written = _emit(records, destination)
    corpus = BoundCorpus(
        path=destination, ids=ids, gold=gold, record_count=len(records),
        written_keys=written,
    )
    corpus.assert_no_gold_written()
    return corpus


def digest() -> str:
    return hashlib.sha256(
        json.dumps(
            {"manifest": load_manifest().as_json(),
             "overlap": list(overlap_with_held_out())},
            sort_keys=True,
        ).encode("utf-8")
    ).hexdigest()
