"""V-2 --- classification and fan-out (`P-2`, Critical).

Detector Reviewer finding 12 named four defects, all fixed here.

*No calibration corpus.* ``routing_corpus.json`` pointed at a manifest that did
not exist, so the calibration obligation passed on a refusal. The excluded
60-message corpus and its manifest are now committed, deterministically
generated by ``tests/tools/freeze-calibration.py``, digest bound, and proved
disjoint from the held-out corpus.

*Product-reported metrics.* Every number came out of the system under test. The
product now supplies only raw per-message predictions under opaque identifiers;
:mod:`acceptance._harness.metrics` joins them to Tester-held gold and computes
macro-F1, per-label precision/recall/F1, shared precision, exact-match
atomisation, private-to-shared detection and abstention itself. The product's
predictions are scored only by the instrument (Validator R-13).

*Pre-opaque identifiers.* Mixed-message lookups used the frozen ``m###`` ids, so
an implementation could memorise the answer key. Every lookup now goes through
the per-run opaque token.

*Sleep-duration crash seams.* The five kill points were labels with a hardcoded
recovery flag. Each transition is now killed at a witnessed point --- an
observed artefact appearing under the store, followed by an observed abnormal
process exit --- and recovery is read back from the store, never reported.
"""

from __future__ import annotations

import contextlib
import hashlib
import json
import os
import signal
import subprocess
import time
import tomllib
from pathlib import Path

import pytest

from ._harness import calibration, metrics
from ._harness import obligations as O
from ._harness import prereq, stats, trust
from ._harness.cli import Kinbase
from ._harness.corpora import PRODUCT_VISIBLE_KEYS, bind_routing_corpus, load_gold
from ._harness.evidence_model import (
    Origin,
    field,
    require_all,
    require_nonempty,
    rows,
)
from ._harness.requirements import (
    ARCH,
    RULING,
    PRODUCT,
    SRC,
    VERIFY,
    ProductFailure,
    spec_ref,
)
from ._harness.roots import ProofRoots
from ._harness.vault import CanaryVault, VaultEntry
from ._harness.worldbuilder import SignedWorld, start_company, start_session, Witness, witness_process_exit

pytestmark = [pytest.mark.v2, pytest.mark.requires_product]

#: The four ratified destination labels, frozen in the harness.
DESTINATIONS: tuple[str, ...] = metrics.DESTINATIONS

#: The two destinations whose precision floor V-2 states separately.
SHARED: tuple[str, ...] = metrics.SHARED_DESTINATIONS

#: The five ratified fan-out transitions a kill must be able to interrupt.
TRANSITIONS: tuple[str, ...] = (
    "nonce_reservation", "event_append_rename", "manifest", "receipt", "apology",
)

#: Journal marker/state vocabulary, not inferred destination data directories.
TRANSITION_MARKERS: dict[str, tuple[str, ...]] = {
    "nonce_reservation": ("nonce_reservation", "nonce_reserved"),
    "event_append_rename": ("event_append_rename", "event_append", "event_rename", "event_appended"),
    "manifest": ("manifest", "manifest_written"),
    "receipt": ("receipt", "receipt_written"),
    "apology": ("apology", "apology_written"),
}

#: The five preregistered classifier runs. Replay freezes from run 1.
RUN_COUNT = 5
REPLAY_RUN = 1

#: Bootstrap seed, frozen so the interval is reproducible.
BOOTSTRAP_SEED = 20260907

#: Seconds the proof clock is advanced to pass a closing deadline.
CLOSING_DEADLINE_OFFSET = 604800


# --------------------------------------------------------------------------
# Fixtures
# --------------------------------------------------------------------------


@pytest.fixture()
def gold_corpus() -> dict:
    return load_gold("routing_corpus.json")


@pytest.fixture()
def anchored(roots: ProofRoots, kinbase: Kinbase):
    world = SignedWorld.create(roots.repo_root)
    anchors = trust.establish(kinbase, roots, world,
                              classifier_model="ollama:qwen2.5:7b")
    trust.classifier_pinned(anchors, what="V-2 classification")
    return world, anchors


@pytest.fixture()
def held_out(roots: ProofRoots, gold_corpus: dict, vault: CanaryVault):
    """The held-out corpus, instantiated with vault-held canary values."""
    values: dict[str, str] = {}
    for slot in sorted(gold_corpus["canary_slots"]):
        value = "kx" + slot + os.urandom(8).hex()
        values[slot] = value
        vault.add(VaultEntry(
            canary_id=slot, raw_value=value, transformation_family="exact",
            planted_surfaces=("routing_corpus",),
            expected_destination_denial=SHARED,
            gold_atom_label="private", gold_destination_labels=("personal",),
        ))
    vault.seal()
    destination = roots.run_root / "corpus" / "held-out.jsonl"
    return bind_routing_corpus(gold_corpus, values, destination)


def _observe(kinbase: Kinbase, repo: Path, corpus: Path, session: str) -> dict:
    """Drive one classifier run over a bound corpus through the real surface."""
    result = kinbase.run(
        "session", "observe", session, "--event", str(corpus), "--json",
        cwd=repo, check=False,
    )
    if result.returncode == 1:
        raise ProductFailure("`session observe` returned the reserved exit 1")
    payload = result.json
    if not isinstance(payload, dict):
        raise ProductFailure("`session observe --json` did not return an object")
    if result.returncode == 0:
        trust.verify_classifier_spawn(kinbase, repo)
    return payload


def _admissions(kinbase: Kinbase, repo: Path, session: str) -> dict:
    """Read private audit records; compute counts from bytes, never a product verdict."""
    from ._harness.admission import audit
    return audit(kinbase, repo, session)


def _run_pool(kinbase: Kinbase, repo: Path, corpus, *, runs: int,
              label: str) -> tuple[list, list[dict]]:
    """Execute the preregistered runs and join each to Tester-held gold."""
    gold = metrics.parse_gold(corpus.gold)
    joins = []
    reported: list[dict] = []
    for index in range(runs):
        session = start_session(kinbase, repo)
        observed = _observe(kinbase, repo, corpus.path, session)
        listing = _admissions(kinbase, repo, session)
        predictions = metrics.parse_predictions(field(listing, "predictions"))
        joins.append(metrics.joined(predictions, gold,
                                    name=label + "-run-" + str(index)))
        reported.append({
            "run": index,
            "model_fingerprint": field(observed, "classifier", "fingerprint"),
            "macro_f1": joins[-1].macro_f1(),
        })
    return joins, reported


def _first_candidate(listing: dict, destination: str | None = None) -> dict:
    candidates = [c for c in rows(listing, "candidates")
                  if destination is None or field(c, "destination") == destination]
    if not candidates:
        raise ProductFailure(
            "the private audit ledger has no candidate for the required destination"
        )
    return candidates[0]



def _fanout_pair(listing: dict, destination: str) -> tuple[dict, dict]:
    for local in rows(listing, "candidates"):
        if field(local, "destination") != destination or not isinstance(field(local, "message_id"), str):
            continue
        for company in rows(listing, "candidates"):
            if field(company, "destination") == "company:root" and field(
                    company, "message_id") == field(local, "message_id"):
                if field(local, "candidate_id") != field(company, "candidate_id"):
                    return local, company
    raise ProductFailure("V-2 fan-out requires independent Codebase and Company "
                         "candidates for the same source message")

def _checkpoint(kinbase: Kinbase, repo: Path, candidate: dict, destination: str, **kwargs):
    return kinbase.run("session", "checkpoint", str(field(candidate, "session_id")),
                       "--json", cwd=repo, check=False, **kwargs)


def _checkpoint_async(kinbase: Kinbase, repo: Path, candidate: dict, destination: str):
    return kinbase.popen("session", "checkpoint", str(field(candidate, "session_id")),
                         "--json", cwd=repo)


# --------------------------------------------------------------------------
# Instrument-owned floors
# --------------------------------------------------------------------------


@spec_ref(
    VERIFY("V-2", "corpus-floors",
           "Tester freezes at least 120 held-out natural messages with gold atom boundaries "
           "and destination sets; at least 40 are mixed and at least 100 contain varied "
           "private/safety canaries or transformations."),
)
@pytest.mark.selftest
def test_held_out_corpus_meets_every_frozen_floor(gold_corpus: dict) -> None:
    """A Tester-owned floor. Failure here is INVALID_HARNESS, never a product fault."""
    messages = prereq.gold_records(
        gold_corpus["messages"], name="held-out routing corpus", minimum=120,
        why="V-2 freezes at least 120 held-out natural messages",
    )
    mixed = [m for m in messages if m["mixed"]]
    canary_bearing = [m for m in messages if m["canary_slots"]]
    O.check(
        "V-2.corpus-floors",
        {
            "held_out_messages": len(messages),
            "mixed_messages": len(mixed),
            "canary_bearing_messages": len(canary_bearing),
            "seeded_canaries": len(gold_corpus["canary_slots"]),
            "strata": sorted({m["stratum"] for m in messages}),
            "gold_withheld_from_product": not (
                {"gold_atoms", "mixed", "stratum"} & set(PRODUCT_VISIBLE_KEYS)
            ),
        },
        label="frozen held-out corpus floors",
    )


@spec_ref(
    VERIFY("V-2", "annotators",
           "Two independent annotators label the routing/atomization gold set before model "
           "execution. Cohen's kappa must be at least 0.80 per destination"),
)
@pytest.mark.selftest
def test_annotator_agreement_and_frozen_adjudication_digest(gold_corpus: dict) -> None:
    annotations = gold_corpus["annotations"]
    first = annotations["annotator_a"]
    second = annotations["annotator_b"]
    shared_ids = prereq.collected(
        sorted(set(first) & set(second)), what="doubly annotated messages",
        minimum=120, why="kappa needs both annotators on the same messages",
    )
    per_destination = [
        {
            "destination": destination,
            "kappa": stats.cohen_kappa(
                [str(destination in first[i]) for i in shared_ids],
                [str(destination in second[i]) for i in shared_ids],
            ),
        }
        for destination in DESTINATIONS
    ]
    O.check(
        "V-2.annotators",
        {
            "per_destination_kappa": per_destination,
            "adjudication_digest": gold_corpus["adjudication_digest"],
            "frozen_before_classifier_runs":
                gold_corpus["adjudication_frozen_before_classifier_runs"],
        },
        label="two independent annotators, frozen adjudication",
    )


# --------------------------------------------------------------------------
# Live classification, measured by the harness
# --------------------------------------------------------------------------


@spec_ref(
    VERIFY("V-2", "pinned-runs",
           "The live semantic classifier executes at least five preregistered runs with pinned "
           "model/version/settings."),
)
def test_five_pinned_runs_lower_bound_meets_macro_f1_and_shared_precision(
    kinbase: Kinbase, anchored, held_out
) -> None:
    world, anchors = anchored
    joins, reported = _run_pool(kinbase, world.repo.path, held_out,
                                runs=RUN_COUNT, label="heldout")
    require_all(
        joins, lambda j: bool(j.tokens), obligation="V-2.pinned-runs",
        why="every preregistered run must produce joinable predictions",
        minimum=RUN_COUNT, origin=Origin.PRODUCT,
    )
    fingerprints = {r["model_fingerprint"] for r in reported}
    O.check(
        "V-2.pinned-runs",
        {
            "run_count": len(joins),
            "distinct_model_fingerprints": len(fingerprints),
            "replay_frozen_from_run": REPLAY_RUN,
            "macro_f1_lower_bound": metrics.pooled_macro_f1_lower_bound(
                joins, seed=BOOTSTRAP_SEED),
            "macro_f1_interval_method": "message_stratified_bootstrap",
            "shared_precision_lower_bound": metrics.pooled_shared_precision(joins),
            "shared_precision_interval_method": "wilson",
            "computed_by_harness_from_raw_predictions": True,
        },
        label="five pinned runs, harness-computed bounds",
    )




@spec_ref(
    SRC("V-2", "SRC-3",
        "We need the system to correctly identify and classify messages."),
    VERIFY("V-2", "atomisation",
           "One mixed message must yield independent Personal and Codebase candidates"),
)
def test_mixed_messages_atomise_rather_than_take_one_label(
    kinbase: Kinbase, anchored, held_out
) -> None:
    world, anchors = anchored
    joins, _ = _run_pool(kinbase, world.repo.path, held_out, runs=1,
                         label="atomisation")
    first = joins[0]
    detail = first.mixed_message_detail()
    require_nonempty(
        detail, obligation="V-2.atomisation",
        why="the held-out corpus declares mixed messages and none were predicted over",
        origin=Origin.PRODUCT,
    )
    O.check(
        "V-2.atomisation",
        {
            "mixed_messages": detail,
            "exact_match_atomization": first.exact_match_atomisation(),
        },
        label="mixed messages atomise rather than take one label",
    )


@spec_ref(
    VERIFY("V-2", "metrics",
           "Compute exact-match atomization, per-label precision/recall/F1, macro-F1, shared "
           "precision, private-to-shared detection, and calibration/abstention."),
)
def test_exact_match_atomization_and_per_label_metrics(
    kinbase: Kinbase, anchored, held_out
) -> None:
    world, anchors = anchored
    session = start_session(kinbase, world.repo.path)
    _observe(kinbase, world.repo.path, held_out.path, session)
    listing = _admissions(kinbase, world.repo.path, session)
    predictions = metrics.parse_predictions(field(listing, "predictions"))
    join = metrics.joined(predictions, metrics.parse_gold(held_out.gold),
                          name="metrics")
    computed = join.per_label_metrics()
    O.check(
        "V-2.metrics",
        {
            "per_label_destinations": sorted(d["destination"] for d in computed),
            "per_label": computed,
            "private_to_shared_detection": join.private_to_shared_detection(),
            "calibration_and_abstention": join.calibration_and_abstention(),
            "harness_recomputation_agrees": metrics.agrees(
                sum(row["f1"] for row in computed) / len(computed), join.macro_f1(),
                tolerance=0.005),
        },
        label="harness-computed per-label metrics",
    )


@spec_ref(
    VERIFY("V-2", "low-confidence",
           "Mutations: whole-message single label; shared-by-default under low confidence;"),
)
def test_low_confidence_shared_label_demotes_to_none_or_unknown(
    kinbase: Kinbase, anchored, held_out
) -> None:
    world, anchors = anchored
    session = start_session(kinbase, world.repo.path)
    _observe(kinbase, world.repo.path, held_out.path, session)
    listing = _admissions(kinbase, world.repo.path, session)
    low_atoms = [
        {"atom_id": field(atom, "atom_id"), "destination": field(atom, "destination")}
        for atom in rows(listing, "atoms")
        if field(atom, "confidence") == "low"
    ]
    O.check(
        "V-2.low-confidence",
        {
            "low_confidence_atom_count": len(low_atoms),
            "low_confidence_atoms": low_atoms,
        },
        label="low confidence never defaults to shared",
    )


@spec_ref(
    VERIFY("V-2", "independent-candidates",
           "another yields Personal, Company, and Codebase candidates with distinct minimized "
           "bytes."),
)
def test_independent_candidates_with_distinct_minimized_bytes(
    kinbase: Kinbase, anchored, held_out
) -> None:
    world, anchors = anchored
    session = start_session(kinbase, world.repo.path)
    _observe(kinbase, world.repo.path, held_out.path, session)
    listing = _admissions(kinbase, world.repo.path, session)
    by_message: dict[str, set[str]] = {}
    digests: dict[str, list[str]] = {}
    for candidate in rows(listing, "candidates"):
        message = field(candidate, "message_id")
        destination = field(candidate, "destination")
        if isinstance(message, str) and isinstance(destination, str):
            by_message.setdefault(message, set()).add(destination)
            digests.setdefault(message, []).append(
                str(field(candidate, "payload_digest")))
    two = [m for m, d in by_message.items() if len(d) == 2]
    three = [m for m, d in by_message.items() if len(d) >= 3]
    O.check(
        "V-2.independent-candidates",
        {
            "two_store_messages": len(two),
            "three_store_messages": len(three),
            "three_store_detail": [
                {"message_id": m, "payload_digests": digests[m]} for m in three
            ],
        },
        label="independent candidates with distinct minimized bytes",
    )


# --------------------------------------------------------------------------
# Fan-out, apology, recovery
# --------------------------------------------------------------------------


@spec_ref(
    RULING("V-2", "partial-fanout", "Independent destination receipts survive partial fan-out; the admitting principal is responsible and a named destination authority closes an orphan."),
)
def test_partial_fanout_failure_does_not_roll_back_committed_destination(
    kinbase: Kinbase, anchored, held_out, roots: ProofRoots
) -> None:
    from ._harness.service import Blackhole

    world, anchors = anchored
    session = start_session(kinbase, world.repo.path)
    with Blackhole(0) as blackhole, anchors.company_endpoint(
        f"http://127.0.0.1:{blackhole.port}"
    ):
        blackholed = _observe(kinbase, world.repo.path, held_out.path, session)
    witness = Witness(kind="company_unreachable")
    witness.note(port=blackhole.port, observation=blackholed)
    witness.require("the Company endpoint must actually have been unreachable")

    status = _admissions(kinbase, world.repo.path, session)
    apology = rows(status, "apologies")
    O.check(
        "V-2.partial-fanout",
        {
            "codebase_receipt_state": field(
                status, "fanout_receipts", "codebase", "state"),
            "company_receipt_state": field(
                status, "fanout_receipts", "company", "state"),
            "apology_count": len(apology),
            "apology": apology[0] if apology else {},
        },
        label="partial fan-out exposes an apology, not a rollback",
    )


@spec_ref(
    VERIFY("V-2", "retry-receipt",
           "retry returns the original receipt without duplication."),
)
def test_retry_returns_original_receipt_without_duplication(
    kinbase: Kinbase, anchored, held_out
) -> None:
    world, anchors = anchored
    session = start_session(kinbase, world.repo.path)
    _observe(kinbase, world.repo.path, held_out.path, session)
    listing = _admissions(kinbase, world.repo.path, session)
    candidate = _first_candidate(listing, "codebase:" + anchors.repository_uuid)
    destination = "codebase:" + anchors.repository_uuid

    first = _checkpoint(kinbase, world.repo.path, candidate, destination)
    events_after_first = world.event_count()
    second = _checkpoint(kinbase, world.repo.path, candidate, destination,
                     env=kinbase.base_env({"KINBASE_PROOF_CLOCK_OFFSET_SECONDS": "960"}))
    events_after_second = world.event_count()
    status = _admissions(kinbase, world.repo.path, session)

    def receipt(result):
        return next((row.get("receipt_id") for row in rows(result.json, "admissions")
                     if row.get("candidate_id") == candidate["candidate_id"]), None)
    first_receipt = receipt(first)
    O.check(
        "V-2.retry-receipt",
        {
            "receipt_ids_equal": (
                first_receipt is not None
                and first_receipt == receipt(second)
            ),
            "second_event_created": events_after_second != events_after_first,
            "duplicate_events": field(status, "duplicate_events"),
        },
        label="retry is idempotent on the receipt",
    )


@spec_ref(
    VERIFY("V-2", "orphan-abandoned",
           "the destination service emits one signed `orphan_abandoned`, names the unresponsive "
           "authority, keeps the fact withdrawn, and leaves no pending orphan forever."),
)
def test_expired_closing_deadline_emits_one_signed_orphan_abandoned(
    kinbase: Kinbase, anchored, held_out
) -> None:
    from ._harness.service import Blackhole

    world, anchors = anchored
    session = start_session(kinbase, world.repo.path)
    with Blackhole(0) as blackhole, anchors.company_endpoint(
        f"http://127.0.0.1:{blackhole.port}"
    ):
        _observe(kinbase, world.repo.path, held_out.path, session)
    require_nonempty(rows(_admissions(kinbase, world.repo.path, session), "apologies"),
                     obligation="V-2.orphan-abandoned", origin=Origin.PRODUCT,
                     why="a partial fan-out must open an orphan before its deadline")

    # Advance the proof clock past the closing deadline. The witness is the
    # expiry state read back from the store, not the request itself.
    advanced = kinbase.run(
        "status", "--repo", str(world.repo.path), "--json",
        cwd=world.repo.path, check=False,
        env=kinbase.base_env({
            "KINBASE_PROOF_CLOCK_OFFSET_SECONDS": str(CLOSING_DEADLINE_OFFSET),
        }),
    )
    witness = Witness(kind="closing_deadline_expired")
    witness.note(offset_seconds=CLOSING_DEADLINE_OFFSET,
                 status_exit=advanced.returncode)
    witness.require("the proof clock advance must have been accepted")

    status = advanced.json if isinstance(advanced.json, dict) else {}
    abandoned = [
        e for e in rows(status, "events")
        if field(e, "disposition") == "orphan_abandoned"
    ]
    O.check(
        "V-2.orphan-abandoned",
        {
            "orphan_abandoned_count": len(abandoned),
            "event": abandoned[0] if abandoned else {},
            "pending_orphans_after_deadline": field(status, "pending_orphans"),
        },
        label="one signed orphan_abandoned, no eternal pending orphan",
    )


def _journal_matches(value, transition: str, candidate: dict) -> bool:
    if isinstance(value, str):
        return value.replace("-", "_") in TRANSITION_MARKERS[transition]
    if isinstance(value, list):
        return any(_journal_matches(v, transition, candidate) for v in value)
    if isinstance(value, dict):
        if field(candidate, "candidate_id") and "candidate_id" in value and value["candidate_id"] != field(candidate, "candidate_id"):
            return False
        return any(_journal_matches(value.get(key), transition, candidate)
                   for key in ("journal_state", "transition", "stage", "state"))
    return False


def _journal_files(kinbase: Kinbase, repo: Path) -> tuple[Path, ...]:
    roots = [repo / ".kin" / "local" / "journal"]
    config = kinbase.xdg_config_home / "kinbase" / "config.toml"
    if config.is_file():
        personal = tomllib.loads(config.read_text())["personal"]["data_root"]
        private = Path(personal)
        roots.append(private / "journal")
        roots.extend(p for p in private.rglob("journal") if p.is_dir())
    return tuple(sorted({p for root in roots for p in root.rglob("*") if p.is_file()}))


def _journal_snapshot(kinbase: Kinbase, repo: Path, candidate: dict,
                      transition: str) -> dict[str, str]:
    observed = {}
    for path in _journal_files(kinbase, repo):
        try:
            raw = path.read_bytes()
        except FileNotFoundError:  # Atomic journal rename during polling.
            continue
        try:
            value = json.loads(raw)
        except (ValueError, UnicodeDecodeError):
            value = raw.decode("utf-8", errors="replace").strip()
        if isinstance(value, dict) and field(candidate, "candidate_id") and "candidate_id" in value and value["candidate_id"] != field(candidate, "candidate_id"):
            continue
        if _journal_matches(value, transition, candidate) or _journal_matches(path.stem, transition, candidate):
            observed[str(path)] = hashlib.sha256(raw).hexdigest()
    return observed


def _journal_status(kinbase: Kinbase, repo: Path, candidate: dict, transition: str):
    status = kinbase.run("status", "--repo", str(repo), "--json", cwd=repo, check=False)
    value = field(status.json, "journal_state")
    return value if _journal_matches(value, transition, candidate) else None


def _kill_at_transition(kinbase: Kinbase, world, candidate: dict,
                        destination: str, transition: str) -> dict:
    """Start a fan-out and kill it once the transition's artefact appears.

    The kill point is *witnessed*, not timed: the harness polls the store for
    the artefact class the transition produces and only then signals the
    process. The witness records the observed artefact, the signal sent and the
    observed exit status, so a run in which the process finished normally cannot
    be reported as an interrupted transition.
    """
    repo = world.repo.path
    before = _journal_snapshot(kinbase, repo, candidate, transition)
    prior_state = _journal_status(kinbase, repo, candidate, transition)
    process = kinbase.popen("session", "observe", candidate["session_id"],
                            "--event", candidate["corpus"], "--json", cwd=repo)
    witness = Witness(kind="crash:" + transition)
    deadline = time.monotonic() + 20.0
    appeared = False
    observed = {}
    last_status = time.monotonic()
    while time.monotonic() < deadline:
        now = _journal_snapshot(kinbase, repo, candidate, transition)
        changed = {p: digest for p, digest in now.items() if before.get(p) != digest}
        if changed:
            appeared = True
            observed = {"journal_markers": changed}
            break
        if process.poll() is not None:
            break
        if time.monotonic() - last_status >= 0.05:
            state = _journal_status(kinbase, repo, candidate, transition)
            last_status = time.monotonic()
            if state is not None and state != prior_state:
                appeared = True
                observed = {"journal_state": state}
                break
        time.sleep(0.001)
    signal_sent = False
    if process.poll() is None:
        try:
            process.send_signal(signal.SIGKILL)
            signal_sent = True
        except ProcessLookupError:
            pass  # A completed transaction is not an interrupted transition.
    try:
        process.communicate(timeout=30)
    except subprocess.TimeoutExpired:
        process.kill()
        process.communicate(timeout=30)
    exit_witness = witness_process_exit(process, "crash:" + transition)
    witness.note(transition=transition, artefact_observed=appeared,
                 observation=observed, signal_sent=signal_sent,
                 exit_status=process.returncode)
    return {
        "transition": transition,
        "crash_witnessed": bool(appeared and signal_sent and process.returncode == -signal.SIGKILL),
        "witness": witness.as_json(),
        "exit_witness": exit_witness.as_json(),
    }


@contextlib.contextmanager
def _crash_world(kinbase: Kinbase, roots: ProofRoots, transition: str):
    """Each kill needs a fresh transaction, not the preceding probe's receipt."""
    layout = ProofRoots.create(roots.run_root / "crash-probes" / transition)
    driver = Kinbase(home=layout.home, xdg_config_home=layout.xdg_config_home,
                      cwd=layout.repo_root, path_prefix=kinbase.path_prefix)
    world = SignedWorld.create(layout.repo_root)
    service = start_company(driver, layout)
    try:
        anchors = trust.establish(driver, layout, world, start_service=service,
                                  classifier_model="ollama:qwen2.5:7b")
        trust.classifier_pinned(anchors, what="V-2 crash recovery")
        yield driver, world, anchors
    finally:
        service.stop()


def _one_fanout_source(corpus, repo):
    # Fixture selection uses held-out gold only inside the tester boundary.
    # The shipping process receives one native message, with no destination hint.
    tokens = {token for token, gold in corpus.gold.items()
              if "company" in gold["destinations"]
              and sum("codebase" in atom[2] for atom in gold["atoms"]) == 1}
    source = next((json.loads(line) for line in corpus.path.read_text().splitlines()
                   if json.loads(line)["id"] in tokens), None)
    if source is None:
        raise prereq.missing("fixture", "single-fanout", "one Codebase atom and Company evidence required")
    path = repo.parent / "one-fanout.jsonl"
    path.write_text(json.dumps(source) + "\n")
    return path


@spec_ref(
    VERIFY("V-2", "crash-recovery",
           "Kill each destination between nonce reservation, event append/rename, manifest, "
           "receipt, and apology transitions, then retry concurrently."),
)
def test_kill_at_every_transition_then_concurrent_retry(
    kinbase: Kinbase, roots: ProofRoots, held_out
) -> None:
    results = []
    for transition in TRANSITIONS:
        with _crash_world(kinbase, roots, transition) as (driver, world, anchors):
            session = start_session(driver, world.repo.path)
            candidate = {"session_id": session, "corpus": str(_one_fanout_source(held_out, world.repo.path))}
            destination = "codebase:" + anchors.repository_uuid
            with contextlib.ExitStack() as perturbation:
                if transition == "apology":
                    from ._harness.service import Blackhole
                    blackhole = perturbation.enter_context(Blackhole(0))
                    perturbation.enter_context(anchors.company_endpoint(
                        f"http://127.0.0.1:{blackhole.port}"))
                    destination = "company:root"
                killed = _kill_at_transition(driver, world, candidate, destination, transition)
                first = _checkpoint_async(driver, world.repo.path, candidate, destination)
                second = _checkpoint_async(driver, world.repo.path, candidate, destination)
                first.communicate(timeout=120)
                second.communicate(timeout=120)
                status = _admissions(driver, world.repo.path, session)
                killed.update({
                    "duplicate_events": field(status, "duplicate_events"),
                    "recursive_apologies": field(status, "recursive_apologies"),
                    "recovered": field(status, "fanout_receipts", "codebase", "state")
                    == "committed",
                    "total_events_after_recovery": field(status, "committed_event_count"),
                })
        results.append(killed)

    require_all(
        results, lambda r: r["crash_witnessed"], obligation="V-2.crash-recovery",
        why="each named transition must actually have been interrupted",
        minimum=len(TRANSITIONS), origin=Origin.HARNESS,
    )
    require_all(
        results, lambda r: r["total_events_after_recovery"] == 1,
        obligation="V-2.crash-recovery", minimum=len(TRANSITIONS),
        why="each independent crash probe leaves exactly one event",
        origin=Origin.PRODUCT,
    )
    O.check(
        "V-2.crash-recovery",
        {
            "transitions": results,
            "total_events_after_recovery": results[-1]["total_events_after_recovery"],
        },
        label="witnessed kill at each transition, then concurrent retry",
    )


@spec_ref(
    RULING("V-2", "no-cross-store", "No cross-store transaction or shared private lineage token exists."),
)
def test_no_cross_store_transaction_exists(
    kinbase: Kinbase, anchored, held_out
) -> None:
    world, anchors = anchored
    session = start_session(kinbase, world.repo.path)
    _observe(kinbase, world.repo.path, held_out.path, session)
    listing = _admissions(kinbase, world.repo.path, session)
    candidate = _first_candidate(listing, "codebase:" + anchors.repository_uuid)
    for destination in ("codebase:" + anchors.repository_uuid, "company:root"):
        _checkpoint(kinbase, world.repo.path, candidate, destination)
    status = _admissions(kinbase, world.repo.path, session)
    receipts = [_receipt_row(status, key) for key in ("codebase", "company")]
    O.check(
        "V-2.no-cross-store",
        {"receipts": receipts},
        label="two independent destination transactions",
    )


def _receipt_row(status: dict, key: str) -> dict:
    row = {
        "destination": key,
        "state": field(status, "fanout_receipts", key, "state"),
    }
    rollback = field(status, "fanout_receipts", key, "global_rollback")
    if rollback is not None:
        row["global_rollback"] = rollback
    return row
