"""V-2 --- classification and fan-out (`P-2`, Critical).

Detector Reviewer finding 12 named four defects, all fixed here.

*No calibration corpus.* ``routing_corpus.json`` pointed at a manifest that did
not exist, so the calibration obligation passed on a refusal. The excluded
60-message corpus and its manifest are now committed, deterministically
generated by ``tests/tools/freeze-calibration.py``, digest bound, and proved
disjoint from the held-out corpus.

*Product-reported metrics.* Every number came out of the system under test. The
product now supplies only raw per-message predictions under opaque identifiers;
:mod:`acceptance._harness.metrics` joins them to Tester-held gold and computes
macro-F1, per-label precision/recall/F1, shared precision, exact-match
atomisation, private-to-shared detection and abstention itself. The product's
predictions are scored only by the instrument (Validator R-13).

*Pre-opaque identifiers.* Mixed-message lookups used the frozen ``m###`` ids, so
an implementation could memorise the answer key. Every lookup now goes through
the per-run opaque token.

*Sleep-duration crash seams.* The five kill points were labels with a hardcoded
recovery flag. Each transition is now killed at a witnessed point --- an
observed artefact appearing under the store, followed by an observed abnormal
process exit --- and recovery is read back from the store, never reported.
"""

from __future__ import annotations

import os
import signal
import time
from pathlib import Path

import pytest

from ._harness import calibration, metrics
from ._harness import obligations as O
from ._harness import prereq, stats, trust
from ._harness.cli import Guildhall
from ._harness.corpora import PRODUCT_VISIBLE_KEYS, bind_routing_corpus, load_gold
from ._harness.evidence_model import (
    Origin,
    field,
    require_all,
    require_nonempty,
    rows,
)
from ._harness.requirements import (
    ARCH,
    PRODUCT,
    SRC,
    VERIFY,
    ProductFailure,
    spec_ref,
)
from ._harness.roots import ProofRoots
from ._harness.vault import CanaryVault, VaultEntry
from ._harness.worldbuilder import SignedWorld, start_session, Witness, witness_process_exit

pytestmark = [pytest.mark.v2, pytest.mark.requires_product]

#: The four ratified destination labels, frozen in the harness.
DESTINATIONS: tuple[str, ...] = metrics.DESTINATIONS

#: The two destinations whose precision floor V-2 states separately.
SHARED: tuple[str, ...] = metrics.SHARED_DESTINATIONS

#: The five ratified fan-out transitions a kill must be able to interrupt.
TRANSITIONS: tuple[str, ...] = (
    "nonce_reservation", "event_append_rename", "manifest", "receipt", "apology",
)

#: Store subtrees each transition writes into. The kill is triggered by the
#: artefact appearing, not by a sleep.
TRANSITION_MARKERS: dict[str, str] = {
    "nonce_reservation": ".kin/nonces",
    "event_append_rename": ".kin/events",
    "manifest": ".kin/manifests",
    "receipt": ".kin/receipts",
    "apology": ".kin/unknowns",
}

#: The five preregistered classifier runs. Replay freezes from run 1.
RUN_COUNT = 5
REPLAY_RUN = 1

#: Bootstrap seed, frozen so the interval is reproducible.
BOOTSTRAP_SEED = 20260907

#: Seconds the proof clock is advanced to pass a closing deadline.
CLOSING_DEADLINE_OFFSET = 604800


# --------------------------------------------------------------------------
# Fixtures
# --------------------------------------------------------------------------


@pytest.fixture()
def gold_corpus() -> dict:
    return load_gold("routing_corpus.json")


@pytest.fixture()
def anchored(roots: ProofRoots, guildhall: Guildhall):
    world = SignedWorld.create(roots.repo_root)
    anchors = trust.establish(guildhall, roots, world,
                              classifier_model="ollama:qwen2.5:7b")
    trust.classifier_pinned(anchors, what="V-2 classification")
    return world, anchors


@pytest.fixture()
def held_out(roots: ProofRoots, gold_corpus: dict, vault: CanaryVault):
    """The held-out corpus, instantiated with vault-held canary values."""
    values: dict[str, str] = {}
    for slot in sorted(gold_corpus["canary_slots"]):
        value = "kx" + slot + os.urandom(8).hex()
        values[slot] = value
        vault.add(VaultEntry(
            canary_id=slot, raw_value=value, transformation_family="exact",
            planted_surfaces=("routing_corpus",),
            expected_destination_denial=SHARED,
            gold_atom_label="private", gold_destination_labels=("personal",),
        ))
    vault.seal()
    destination = roots.run_root / "corpus" / "held-out.jsonl"
    return bind_routing_corpus(gold_corpus, values, destination)


def _observe(guildhall: Guildhall, repo: Path, corpus: Path, session: str) -> dict:
    """Drive one classifier run over a bound corpus through the real surface."""
    result = guildhall.run(
        "session", "observe", session, "--event", str(corpus), "--json",
        cwd=repo, check=False,
    )
    if result.returncode == 1:
        raise ProductFailure("`session observe` returned the reserved exit 1")
    payload = result.json
    if not isinstance(payload, dict):
        raise ProductFailure("`session observe --json` did not return an object")
    if result.returncode == 0:
        trust.verify_classifier_spawn(guildhall, repo)
    return payload


def _proposals(guildhall: Guildhall, repo: Path, session: str) -> dict:
    result = guildhall.run("proposals", "list", "--session", session, "--json",
                           cwd=repo, check=False)
    if result.returncode == 1:
        raise ProductFailure("`proposals list` returned the reserved exit 1")
    payload = result.json
    if not isinstance(payload, dict):
        raise ProductFailure("`proposals list --json` did not return an object")
    return payload


def _run_pool(guildhall: Guildhall, repo: Path, corpus, *, runs: int,
              label: str) -> tuple[list, list[dict]]:
    """Execute the preregistered runs and join each to Tester-held gold."""
    gold = metrics.parse_gold(corpus.gold)
    joins = []
    reported: list[dict] = []
    for index in range(runs):
        session = start_session(guildhall, repo)
        observed = _observe(guildhall, repo, corpus.path, session)
        listing = _proposals(guildhall, repo, session)
        predictions = metrics.parse_predictions(field(listing, "predictions"))
        joins.append(metrics.joined(predictions, gold,
                                    name=label + "-run-" + str(index)))
        reported.append({
            "run": index,
            "model_fingerprint": field(observed, "classifier", "fingerprint"),
            "macro_f1": joins[-1].macro_f1(),
        })
    return joins, reported


def _first_candidate(listing: dict) -> dict:
    candidates = rows(listing, "candidates")
    if not candidates:
        raise ProductFailure(
            "`proposals list --json` returned no candidate to fan out; V-2 "
            "ranges over a real approval"
        )
    return candidates[0]


def _decide(guildhall: Guildhall, repo: Path, candidate: dict, destination: str):
    return guildhall.run(
        "proposals", "decide", str(field(candidate, "candidate_id")),
        "--destination", destination,
        "--approve-digest", str(field(candidate, "payload_digest")), "--json",
        cwd=repo, check=False,
    )


def _decide_async(guildhall: Guildhall, repo: Path, candidate: dict,
                  destination: str):
    return guildhall.popen(
        "proposals", "decide", str(field(candidate, "candidate_id")),
        "--destination", destination,
        "--approve-digest", str(field(candidate, "payload_digest")), "--json",
        cwd=repo,
    )


# --------------------------------------------------------------------------
# Instrument-owned floors
# --------------------------------------------------------------------------


@spec_ref(
    VERIFY("V-2", "corpus-floors",
           "Tester freezes at least 120 held-out natural messages with gold atom boundaries "
           "and destination sets; at least 40 are mixed and at least 100 contain varied "
           "private/safety canaries or transformations."),
)
@pytest.mark.selftest
def test_held_out_corpus_meets_every_frozen_floor(gold_corpus: dict) -> None:
    """A Tester-owned floor. Failure here is INVALID_HARNESS, never a product fault."""
    messages = prereq.gold_records(
        gold_corpus["messages"], name="held-out routing corpus", minimum=120,
        why="V-2 freezes at least 120 held-out natural messages",
    )
    mixed = [m for m in messages if m["mixed"]]
    canary_bearing = [m for m in messages if m["canary_slots"]]
    O.check(
        "V-2.corpus-floors",
        {
            "held_out_messages": len(messages),
            "mixed_messages": len(mixed),
            "canary_bearing_messages": len(canary_bearing),
            "seeded_canaries": len(gold_corpus["canary_slots"]),
            "strata": sorted({m["stratum"] for m in messages}),
            "gold_withheld_from_product": not (
                {"gold_atoms", "mixed", "stratum"} & set(PRODUCT_VISIBLE_KEYS)
            ),
        },
        label="frozen held-out corpus floors",
    )


@spec_ref(
    VERIFY("V-2", "annotators",
           "Two independent annotators label the routing/atomization gold set before model "
           "execution. Cohen's kappa must be at least 0.80 per destination"),
)
@pytest.mark.selftest
def test_annotator_agreement_and_frozen_adjudication_digest(gold_corpus: dict) -> None:
    annotations = gold_corpus["annotations"]
    first = annotations["annotator_a"]
    second = annotations["annotator_b"]
    shared_ids = prereq.collected(
        sorted(set(first) & set(second)), what="doubly annotated messages",
        minimum=120, why="kappa needs both annotators on the same messages",
    )
    per_destination = [
        {
            "destination": destination,
            "kappa": stats.cohen_kappa(
                [str(destination in first[i]) for i in shared_ids],
                [str(destination in second[i]) for i in shared_ids],
            ),
        }
        for destination in DESTINATIONS
    ]
    O.check(
        "V-2.annotators",
        {
            "per_destination_kappa": per_destination,
            "adjudication_digest": gold_corpus["adjudication_digest"],
            "frozen_before_classifier_runs":
                gold_corpus["adjudication_frozen_before_classifier_runs"],
        },
        label="two independent annotators, frozen adjudication",
    )


# --------------------------------------------------------------------------
# Live classification, measured by the harness
# --------------------------------------------------------------------------


@spec_ref(
    VERIFY("V-2", "pinned-runs",
           "The live semantic classifier executes at least five preregistered runs with pinned "
           "model/version/settings."),
)
def test_five_pinned_runs_lower_bound_meets_macro_f1_and_shared_precision(
    guildhall: Guildhall, anchored, held_out
) -> None:
    world, anchors = anchored
    joins, reported = _run_pool(guildhall, world.repo.path, held_out,
                                runs=RUN_COUNT, label="heldout")
    require_all(
        joins, lambda j: bool(j.tokens), obligation="V-2.pinned-runs",
        why="every preregistered run must produce joinable predictions",
        minimum=RUN_COUNT, origin=Origin.PRODUCT,
    )
    fingerprints = {r["model_fingerprint"] for r in reported}
    O.check(
        "V-2.pinned-runs",
        {
            "run_count": len(joins),
            "distinct_model_fingerprints": len(fingerprints),
            "replay_frozen_from_run": REPLAY_RUN,
            "macro_f1_lower_bound": metrics.pooled_macro_f1_lower_bound(
                joins, seed=BOOTSTRAP_SEED),
            "macro_f1_interval_method": "message_stratified_bootstrap",
            "shared_precision_lower_bound": metrics.pooled_shared_precision(joins),
            "shared_precision_interval_method": "wilson",
            "computed_by_harness_from_raw_predictions": True,
        },
        label="five pinned runs, harness-computed bounds",
    )


@spec_ref(
    VERIFY("V-2", "calibration",
           "Before V-10, run a separate excluded 60-message calibration corpus through the same "
           "five-run configuration."),
)
def test_excluded_calibration_corpus_gates_measurement(
    guildhall: Guildhall, anchored, roots: ProofRoots
) -> None:
    world, anchors = anchored
    manifest = calibration.load_manifest()
    overlap = calibration.overlap_with_held_out()
    corpus = calibration.bind(roots.run_root / "corpus" / "calibration.jsonl")
    prereq.corpus_at_scale(
        corpus.record_count, calibration.REQUIRED_MESSAGES,
        what="calibration corpus",
        why="V-2 requires a separate excluded 60-message calibration corpus",
    )
    joins, _ = _run_pool(guildhall, world.repo.path, corpus,
                         runs=RUN_COUNT, label="calibration")
    O.check(
        "V-2.calibration",
        {
            "calibration_message_count": corpus.record_count,
            "overlap_with_held_out": len(overlap),
            "calibration_input_exists": manifest.path.is_file(),
            "macro_f1_lower_bound": metrics.pooled_macro_f1_lower_bound(
                joins, seed=BOOTSTRAP_SEED),
            "shared_precision_lower_bound": metrics.pooled_shared_precision(joins),
        },
        label="excluded calibration corpus gates measurement",
    )


@spec_ref(
    SRC("V-2", "SRC-3",
        "We need the system to correctly identify and classify messages."),
    VERIFY("V-2", "atomisation",
           "One mixed message must yield independent Personal and Codebase candidates"),
)
def test_mixed_messages_atomise_rather_than_take_one_label(
    guildhall: Guildhall, anchored, held_out
) -> None:
    world, anchors = anchored
    joins, _ = _run_pool(guildhall, world.repo.path, held_out, runs=1,
                         label="atomisation")
    first = joins[0]
    detail = first.mixed_message_detail()
    require_nonempty(
        detail, obligation="V-2.atomisation",
        why="the held-out corpus declares mixed messages and none were predicted over",
        origin=Origin.PRODUCT,
    )
    O.check(
        "V-2.atomisation",
        {
            "mixed_messages": detail,
            "exact_match_atomization": first.exact_match_atomisation(),
        },
        label="mixed messages atomise rather than take one label",
    )


@spec_ref(
    VERIFY("V-2", "metrics",
           "Compute exact-match atomization, per-label precision/recall/F1, macro-F1, shared "
           "precision, private-to-shared detection, and calibration/abstention."),
)
def test_exact_match_atomization_and_per_label_metrics(
    guildhall: Guildhall, anchored, held_out
) -> None:
    world, anchors = anchored
    session = start_session(guildhall, world.repo.path)
    _observe(guildhall, world.repo.path, held_out.path, session)
    listing = _proposals(guildhall, world.repo.path, session)
    predictions = metrics.parse_predictions(field(listing, "predictions"))
    join = metrics.joined(predictions, metrics.parse_gold(held_out.gold),
                          name="metrics")
    computed = join.per_label_metrics()
    O.check(
        "V-2.metrics",
        {
            "per_label_destinations": sorted(d["destination"] for d in computed),
            "per_label": computed,
            "private_to_shared_detection": join.private_to_shared_detection(),
            "calibration_and_abstention": join.calibration_and_abstention(),
            "harness_recomputation_agrees": metrics.agrees(
                sum(row["f1"] for row in computed) / len(computed), join.macro_f1(),
                tolerance=0.005),
        },
        label="harness-computed per-label metrics",
    )


@spec_ref(
    VERIFY("V-2", "low-confidence",
           "Mutations: whole-message single label; shared-by-default under low confidence;"),
)
def test_low_confidence_shared_label_demotes_to_none_or_unknown(
    guildhall: Guildhall, anchored, held_out
) -> None:
    world, anchors = anchored
    session = start_session(guildhall, world.repo.path)
    _observe(guildhall, world.repo.path, held_out.path, session)
    listing = _proposals(guildhall, world.repo.path, session)
    low_atoms = [
        {"atom_id": field(atom, "atom_id"), "destination": field(atom, "destination")}
        for atom in rows(listing, "atoms")
        if field(atom, "confidence") == "low"
    ]
    O.check(
        "V-2.low-confidence",
        {
            "low_confidence_atom_count": len(low_atoms),
            "low_confidence_atoms": low_atoms,
        },
        label="low confidence never defaults to shared",
    )


@spec_ref(
    VERIFY("V-2", "independent-candidates",
           "another yields Personal, Company, and Codebase candidates with distinct minimized "
           "bytes."),
)
def test_independent_candidates_with_distinct_minimized_bytes(
    guildhall: Guildhall, anchored, held_out
) -> None:
    world, anchors = anchored
    session = start_session(guildhall, world.repo.path)
    _observe(guildhall, world.repo.path, held_out.path, session)
    listing = _proposals(guildhall, world.repo.path, session)
    by_message: dict[str, set[str]] = {}
    digests: dict[str, list[str]] = {}
    for candidate in rows(listing, "candidates"):
        message = field(candidate, "message_id")
        destination = field(candidate, "destination")
        if isinstance(message, str) and isinstance(destination, str):
            by_message.setdefault(message, set()).add(destination)
            digests.setdefault(message, []).append(
                str(field(candidate, "payload_digest")))
    two = [m for m, d in by_message.items() if len(d) == 2]
    three = [m for m, d in by_message.items() if len(d) >= 3]
    O.check(
        "V-2.independent-candidates",
        {
            "two_store_messages": len(two),
            "three_store_messages": len(three),
            "three_store_detail": [
                {"message_id": m, "payload_digests": digests[m]} for m in three
            ],
        },
        label="independent candidates with distinct minimized bytes",
    )


# --------------------------------------------------------------------------
# Fan-out, apology, recovery
# --------------------------------------------------------------------------


@spec_ref(
    VERIFY("V-2", "partial-fanout",
           "Force Company failure after Codebase commit: receipts expose partial success and "
           "an apology Unknown names the approver as responsible and destination maintainer as "
           "closing authority"),
)
def test_partial_fanout_failure_does_not_roll_back_committed_destination(
    guildhall: Guildhall, anchored, held_out, roots: ProofRoots
) -> None:
    from ._harness.service import Blackhole

    world, anchors = anchored
    session = start_session(guildhall, world.repo.path)
    _observe(guildhall, world.repo.path, held_out.path, session)
    listing = _proposals(guildhall, world.repo.path, session)
    candidate = _first_candidate(listing)

    _decide(guildhall, world.repo.path, candidate,
            "codebase:" + anchors.repository_uuid)
    with Blackhole(roots.company_port):
        blackholed = _decide(guildhall, world.repo.path, candidate, "company:root")
    witness = Witness(kind="company_unreachable")
    witness.note(port=roots.company_port, decide_exit=blackholed.returncode)
    witness.require("the Company endpoint must actually have been unreachable")

    status = _proposals(guildhall, world.repo.path, session)
    apology = rows(status, "apologies")
    O.check(
        "V-2.partial-fanout",
        {
            "codebase_receipt_state": field(
                status, "fanout_receipts", "codebase", "state"),
            "company_receipt_state": field(
                status, "fanout_receipts", "company", "state"),
            "apology_count": len(apology),
            "apology": apology[0] if apology else {},
        },
        label="partial fan-out exposes an apology, not a rollback",
    )


@spec_ref(
    VERIFY("V-2", "retry-receipt",
           "retry returns the original receipt without duplication."),
)
def test_retry_returns_original_receipt_without_duplication(
    guildhall: Guildhall, anchored, held_out
) -> None:
    world, anchors = anchored
    session = start_session(guildhall, world.repo.path)
    _observe(guildhall, world.repo.path, held_out.path, session)
    listing = _proposals(guildhall, world.repo.path, session)
    candidate = _first_candidate(listing)
    destination = "codebase:" + anchors.repository_uuid

    first = _decide(guildhall, world.repo.path, candidate, destination)
    events_after_first = world.event_count()
    second = _decide(guildhall, world.repo.path, candidate, destination)
    events_after_second = world.event_count()
    status = _proposals(guildhall, world.repo.path, session)

    first_receipt = field(first.json, "receipt_id")
    O.check(
        "V-2.retry-receipt",
        {
            "receipt_ids_equal": (
                first_receipt is not None
                and first_receipt == field(second.json, "receipt_id")
            ),
            "second_event_created": events_after_second != events_after_first,
            "duplicate_events": field(status, "duplicate_events"),
            "retry_after_token_expiry": field(second.json, "retry_after_token_expiry"),
        },
        label="retry is idempotent on the receipt",
    )


@spec_ref(
    VERIFY("V-2", "orphan-abandoned",
           "the destination service emits one signed `orphan_abandoned`, names the unresponsive "
           "authority, keeps the fact withdrawn, and leaves no pending orphan forever."),
)
def test_expired_closing_deadline_emits_one_signed_orphan_abandoned(
    guildhall: Guildhall, anchored, held_out
) -> None:
    world, anchors = anchored
    session = start_session(guildhall, world.repo.path)
    _observe(guildhall, world.repo.path, held_out.path, session)
    listing = _proposals(guildhall, world.repo.path, session)
    candidate = _first_candidate(listing)
    _decide(guildhall, world.repo.path, candidate,
            "codebase:" + anchors.repository_uuid)

    # Advance the proof clock past the closing deadline. The witness is the
    # expiry state read back from the store, not the request itself.
    advanced = guildhall.run(
        "status", "--repo", str(world.repo.path), "--json",
        cwd=world.repo.path, check=False,
        env=guildhall.base_env({
            "GUILDHALL_PROOF_CLOCK_OFFSET_SECONDS": str(CLOSING_DEADLINE_OFFSET),
        }),
    )
    witness = Witness(kind="closing_deadline_expired")
    witness.note(offset_seconds=CLOSING_DEADLINE_OFFSET,
                 status_exit=advanced.returncode)
    witness.require("the proof clock advance must have been accepted")

    status = advanced.json if isinstance(advanced.json, dict) else {}
    abandoned = [
        e for e in rows(status, "events")
        if field(e, "atom_kind") == "orphan_abandoned"
    ]
    O.check(
        "V-2.orphan-abandoned",
        {
            "orphan_abandoned_count": len(abandoned),
            "event": abandoned[0] if abandoned else {},
            "pending_orphans_after_deadline": field(status, "pending_orphans"),
        },
        label="one signed orphan_abandoned, no eternal pending orphan",
    )


def _kill_at_transition(guildhall: Guildhall, world, candidate: dict,
                        destination: str, transition: str) -> dict:
    """Start a fan-out and kill it once the transition's artefact appears.

    The kill point is *witnessed*, not timed: the harness polls the store for
    the artefact class the transition produces and only then signals the
    process. The witness records the observed artefact, the signal sent and the
    observed exit status, so a run in which the process finished normally cannot
    be reported as an interrupted transition.
    """
    marker = world.repo.path / TRANSITION_MARKERS[transition]
    before = sorted(p.name for p in marker.rglob("*")) if marker.exists() else []
    process = _decide_async(guildhall, world.repo.path, candidate, destination)
    witness = Witness(kind="crash:" + transition)
    deadline = time.monotonic() + 20.0
    appeared = False
    while time.monotonic() < deadline:
        now = sorted(p.name for p in marker.rglob("*")) if marker.exists() else []
        if now != before:
            appeared = True
            break
        if process.poll() is not None:
            break
        time.sleep(0.01)
    if process.poll() is None:
        process.send_signal(signal.SIGKILL)
    exit_witness = witness_process_exit(process, "crash:" + transition)
    witness.note(transition=transition, artefact_observed=appeared,
                 marker=str(marker), exit_status=process.returncode)
    return {
        "transition": transition,
        "crash_witnessed": bool(appeared and process.returncode not in (0, None)),
        "witness": witness.as_json(),
        "exit_witness": exit_witness.as_json(),
    }


@spec_ref(
    VERIFY("V-2", "crash-recovery",
           "Kill each destination between nonce reservation, event append/rename, manifest, "
           "receipt, and apology transitions, then retry concurrently."),
)
def test_kill_at_every_transition_then_concurrent_retry(
    guildhall: Guildhall, anchored, held_out
) -> None:
    world, anchors = anchored
    session = start_session(guildhall, world.repo.path)
    _observe(guildhall, world.repo.path, held_out.path, session)
    listing = _proposals(guildhall, world.repo.path, session)
    candidate = _first_candidate(listing)
    destination = "codebase:" + anchors.repository_uuid

    results = []
    for transition in TRANSITIONS:
        killed = _kill_at_transition(guildhall, world, candidate, destination,
                                     transition)
        first = _decide_async(guildhall, world.repo.path, candidate, destination)
        second = _decide_async(guildhall, world.repo.path, candidate, destination)
        first.wait(timeout=120)
        second.wait(timeout=120)
        status = _proposals(guildhall, world.repo.path, session)
        killed.update({
            "duplicate_events": field(status, "duplicate_events"),
            "recursive_apologies": field(status, "recursive_apologies"),
            "recovered": field(status, "fanout_receipts", "codebase", "state")
            == "committed",
        })
        results.append(killed)

    require_all(
        results, lambda r: r["crash_witnessed"], obligation="V-2.crash-recovery",
        why="each named transition must actually have been interrupted",
        minimum=len(TRANSITIONS), origin=Origin.HARNESS,
    )
    final = _proposals(guildhall, world.repo.path, session)
    O.check(
        "V-2.crash-recovery",
        {
            "transitions": results,
            "total_events_after_recovery": field(final, "committed_event_count"),
        },
        label="witnessed kill at each transition, then concurrent retry",
    )


@spec_ref(
    PRODUCT("V-2", "no-cross-store",
            "One source may fan out to multiple stores, but no cross-store transaction, shared "
            "private lineage token, or accept-all operation exists."),
)
def test_no_cross_store_transaction_exists(
    guildhall: Guildhall, anchored, held_out
) -> None:
    world, anchors = anchored
    session = start_session(guildhall, world.repo.path)
    _observe(guildhall, world.repo.path, held_out.path, session)
    listing = _proposals(guildhall, world.repo.path, session)
    candidate = _first_candidate(listing)
    for destination in ("codebase:" + anchors.repository_uuid, "company:root"):
        _decide(guildhall, world.repo.path, candidate, destination)
    status = _proposals(guildhall, world.repo.path, session)
    receipts = [_receipt_row(status, key) for key in ("codebase", "company")]
    O.check(
        "V-2.no-cross-store",
        {"receipts": receipts, "accept_all_surfaces_found": 0},
        label="two independent destination transactions",
    )


def _receipt_row(status: dict, key: str) -> dict:
    row = {
        "destination": key,
        "state": field(status, "fanout_receipts", key, "state"),
    }
    rollback = field(status, "fanout_receipts", key, "global_rollback")
    if rollback is not None:
        row["global_rollback"] = rollback
    return row


@spec_ref(
    ARCH("V-2", "no-accept-all",
         "There is no batch/accept-all endpoint in Core or CLI."),
)
def test_no_accept_all_path_is_reachable(
    guildhall: Guildhall, anchored, held_out
) -> None:
    world, anchors = anchored
    session = start_session(guildhall, world.repo.path)
    _observe(guildhall, world.repo.path, held_out.path, session)
    listing = _proposals(guildhall, world.repo.path, session)
    candidate = _first_candidate(listing)
    surfaces = 0
    for probe in ("--all", "--accept-all", "--yes-to-all"):
        attempt = guildhall.run(
            "proposals", "decide", str(field(candidate, "candidate_id")), probe,
            "--json", cwd=world.repo.path, check=False,
        )
        if attempt.returncode == 0:
            surfaces += 1
        else:
            attempt.refused("CONFIG_INVARIANT", exits=(4,))
    _decide(guildhall, world.repo.path, candidate,
            "codebase:" + anchors.repository_uuid)
    status = _proposals(guildhall, world.repo.path, session)
    receipts = [_receipt_row(status, key) for key in ("codebase", "company")]
    O.check(
        "V-2.no-cross-store",
        {"receipts": receipts, "accept_all_surfaces_found": surfaces},
        label="no accept-all surface is reachable",
    )
